
import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "../styles/globals.css";
import "../styles/style.css";
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";

const sora = Sora({
  variable: "--font-sora-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Identity Hub",
  description: "Identity-hub is a better way to achieve privacyGenerated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sora.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
